[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
realfft = "3.0.0"
dasp = { version = "0.11.0", features = ["signal", "signal-window", "signal-window-hanning", "window-hanning"] }
assert_no_alloc = "1.1.2"
rand = "0.8.5"
